name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./webapp
          push: true
          tags: jimleroux/webapp:${{ github.sha }}

      - name: Run tests
        run: |
          cat webapp/app/script.js

      - name: Run tests
        run: |
          docker run --rm -d -p 8080:80 jimleroux/webapp:latest

      - name: Wait for container to be ready
        run: sleep 5

      - name: Test running container
        run: |
          for i in {1..5}; do
            curl -f http://localhost:8080 && break || sleep 5;
          done
          if [ $? -ne 0 ]; then
            docker logs $(docker ps -q) && exit 1
          fi

      - name: Set up Azure CLI
        run: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: Get AKS credentials
        run: |
          az aks get-credentials --resource-group rg-webapp --name webapp

      - name: Deploy to AKS
        run: |
          kubectl set image deployment/webapp-deployment webapp-container=jimleroux/webapp:${{ github.sha }}


